//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporitelna.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool btntDetails1Cache {
            get {
                return ((bool)(this["btntDetails1Cache"]));
            }
            set {
                this["btntDetails1Cache"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P:\\PAM\\MZDY.T_0")]
        public string txtAsPath {
            get {
                return ((string)(this["txtAsPath"]));
            }
            set {
                this["txtAsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P:\\PAM\\holding\\MZDY.T_1")]
        public string txtHoldingPath {
            get {
                return ((string)(this["txtHoldingPath"]));
            }
            set {
                this["txtHoldingPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P:\\PAM\\bus\\MZDY.T_1")]
        public string txtBusPath {
            get {
                return ((string)(this["txtBusPath"]));
            }
            set {
                this["txtBusPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P:\\PAM\\logistics\\MZDY.T_1")]
        public string txtLogisticsPath {
            get {
                return ((string)(this["txtLogisticsPath"]));
            }
            set {
                this["txtLogisticsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P:\\PAM\\servis\\MZDY.T_1")]
        public string txtServisPath {
            get {
                return ((string)(this["txtServisPath"]));
            }
            set {
                this["txtServisPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool usersIdChecked {
            get {
                return ((bool)(this["usersIdChecked"]));
            }
            set {
                this["usersIdChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool usersTitulChecked {
            get {
                return ((bool)(this["usersTitulChecked"]));
            }
            set {
                this["usersTitulChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool usersFirstNameChecked {
            get {
                return ((bool)(this["usersFirstNameChecked"]));
            }
            set {
                this["usersFirstNameChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool usersLastNameChecked {
            get {
                return ((bool)(this["usersLastNameChecked"]));
            }
            set {
                this["usersLastNameChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool usersAddressChecked {
            get {
                return ((bool)(this["usersAddressChecked"]));
            }
            set {
                this["usersAddressChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool usersNationalityChecked {
            get {
                return ((bool)(this["usersNationalityChecked"]));
            }
            set {
                this["usersNationalityChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool usersBirthdateChecked {
            get {
                return ((bool)(this["usersBirthdateChecked"]));
            }
            set {
                this["usersBirthdateChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool usersCompanyChecked {
            get {
                return ((bool)(this["usersCompanyChecked"]));
            }
            set {
                this["usersCompanyChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("114")]
        public int dgvUsersWidth0 {
            get {
                return ((int)(this["dgvUsersWidth0"]));
            }
            set {
                this["dgvUsersWidth0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("114")]
        public int dgvUsersWidth1 {
            get {
                return ((int)(this["dgvUsersWidth1"]));
            }
            set {
                this["dgvUsersWidth1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("212")]
        public int dgvUsersWidth2 {
            get {
                return ((int)(this["dgvUsersWidth2"]));
            }
            set {
                this["dgvUsersWidth2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("211")]
        public int dgvUsersWidth3 {
            get {
                return ((int)(this["dgvUsersWidth3"]));
            }
            set {
                this["dgvUsersWidth3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("227")]
        public int dgvUsersWidth4 {
            get {
                return ((int)(this["dgvUsersWidth4"]));
            }
            set {
                this["dgvUsersWidth4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("212")]
        public int dgvUsersWidth5 {
            get {
                return ((int)(this["dgvUsersWidth5"]));
            }
            set {
                this["dgvUsersWidth5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("213")]
        public int dgvUsersWidth6 {
            get {
                return ((int)(this["dgvUsersWidth6"]));
            }
            set {
                this["dgvUsersWidth6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("212")]
        public int dgvUsersWidth7 {
            get {
                return ((int)(this["dgvUsersWidth7"]));
            }
            set {
                this["dgvUsersWidth7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool contractsIdChecked {
            get {
                return ((bool)(this["contractsIdChecked"]));
            }
            set {
                this["contractsIdChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool contractsFirstNameChecked {
            get {
                return ((bool)(this["contractsFirstNameChecked"]));
            }
            set {
                this["contractsFirstNameChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool contractsLastNameChecked {
            get {
                return ((bool)(this["contractsLastNameChecked"]));
            }
            set {
                this["contractsLastNameChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool contractsFullNameChecked {
            get {
                return ((bool)(this["contractsFullNameChecked"]));
            }
            set {
                this["contractsFullNameChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool contractsFinalAmountChecked {
            get {
                return ((bool)(this["contractsFinalAmountChecked"]));
            }
            set {
                this["contractsFinalAmountChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool contractsInterestRateChecked {
            get {
                return ((bool)(this["contractsInterestRateChecked"]));
            }
            set {
                this["contractsInterestRateChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool contractsTotalChecked {
            get {
                return ((bool)(this["contractsTotalChecked"]));
            }
            set {
                this["contractsTotalChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool contractsCurrencyChecked {
            get {
                return ((bool)(this["contractsCurrencyChecked"]));
            }
            set {
                this["contractsCurrencyChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool contractsDateSinceChecked {
            get {
                return ((bool)(this["contractsDateSinceChecked"]));
            }
            set {
                this["contractsDateSinceChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool contractsDateToChecked {
            get {
                return ((bool)(this["contractsDateToChecked"]));
            }
            set {
                this["contractsDateToChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool contractsDescriptionChecked {
            get {
                return ((bool)(this["contractsDescriptionChecked"]));
            }
            set {
                this["contractsDescriptionChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool contractsStatusChecked {
            get {
                return ((bool)(this["contractsStatusChecked"]));
            }
            set {
                this["contractsStatusChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2022")]
        public string cbFilterSelectedYear {
            get {
                return ((string)(this["cbFilterSelectedYear"]));
            }
            set {
                this["cbFilterSelectedYear"] = value;
            }
        }
    }
}
